camera_matrix:
  cols: 3
  data:
  - 529.2313091286234
  - 0.0
  - 343.3808595867481
  - 0.0
  - 529.2487274268415
  - 258.4259923425703
  - 0.0
  - 0.0
  - 1.0
  rows: 3
distortion_coefficients:
  cols: 5
  data:
  - -0.5101638240978964
  - 0.3677438856037903
  - -0.0022833938928634285
  - 0.007833043056298294
  - -0.2524610770369533
  rows: 1
