camera_matrix:
  cols: 3
  data:
  - 428.7562895974783
  - 0.0
  - 326.6643709627298
  - 0.0
  - 415.00629777280864
  - 275.59469129744
  - 0.0
  - 0.0
  - 1.0
  rows: 3
distortion_coefficients:
  cols: 5
  data:
  - -0.504505142631005
  - 0.19655401542299689
  - -0.004733722299319926
  - -0.001770484612887038
  - 0.09943182098732414
  rows: 1
